### ISSUE TITLE
Service Principal Client Secret is not a required field, but deployment using Azure AD will fail without it 

### ISSUE THREAD

**Issue by alexsmithMSFT** [MicrosoftDocs/azure-stack-docs#106]
Deploy Kubernetes, Step "11. Enter the Service Principal Client Secret that you created when creating your service principal."

Service Principal Client Secret is not a mandatory field in the admin portal interface and no warning is presented if it is left blank, but this value *is* required for Azure AD (this doc) and the deployment will fail without it. Suggest updating this step to mention it is mandatory for Azure AD deployments. This was confirmed by PG.

This field is not mandatory because it is not required for AD FS deployment, which is covered in another doc. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b60c4726-881a-a32c-6a85-25ca65a31c00
* Version Independent ID: a40334b6-dca7-52f7-62c3-3b8ecba6d606
* Content: [Deploy Kubernetes to Azure Stack using Azure Active Directory (Azure AD)](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-solution-template-kubernetes-azuread#2-kubernetes-cluster-settings)
* Content Source: [azure-stack/user/azure-stack-solution-template-kubernetes-azuread.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-solution-template-kubernetes-azuread.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by TravisCragg-MSFT** [comment]
@alexsmithMSFT Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by mattbriggs** [comment]
@alexsmithMSFT Creating the service principle for a Kubernetes deployment is in the process for this doc and mentioned in the https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-solution-template-kubernetes-azuread#create-a-service-principal section. In the context of using an Azure AD deployment with Kubernetes, the instructions have you create a secret in Create a service principal, Step 5, and then add the secret in Deploy Kubernetes, Step 11. Can you let me know which issue you encountered so that I can update the doc? Thanks! #in-progress

**Comment by mattbriggs** [comment]
@alexsmithMSFT #Thanks again for your comment. If you need addition information, please let me know. #please-close

**Comment by TravisCragg-MSFT** [comment]
@alexsmithMSFT We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
