### ISSUE TITLE
Bad powershell for "sign in as a user"

### ISSUE THREAD

**Issue by yellowpanda** [MicrosoftDocs/azure-stack-docs#1322]
Section: "Connect with Azure CLI" and "AD FS on Windows" you write:

> **Sign in as a user**:
> 
> You can either specify the username and password directly within the az login command, or authenticate by using a browser. You must do the latter if your account has multi-factor authentication enabled:
> 
>```
> az cloud register  -n <environmentname>   --endpoint-resource-manager "https://management.local.azurestack.external"  --suffix-storage-endpoint "local.azurestack.external" --suffix-keyvault-dns ".vault.local.azurestack.external" --endpoint-vm-image-alias-doc <URI of the document which contains VM image aliases>   --profile "2019-03-01-hybrid"
> ```

The powershell in the example seems to be a copy/past error and is not related to sign in at all. Consider revisit this section. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583c4bab-c16a-a723-04ac-b3265d9e8269
* Version Independent ID: e6ecb0ee-2303-a7ed-9fca-767e3d3bfe86
* Content: [Manage Azure Stack Hub with Azure CLI - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-version-profiles-azurecli2?view=azs-2008&tabs=adfs-win#feedback)
* Content Source: [azure-stack/user/azure-stack-version-profiles-azurecli2.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-version-profiles-azurecli2.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by SaiKishor-MSFT** [comment]
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by TravisCragg-MSFT** [comment]
@yellowpanda Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by mattbriggs** [comment]
@yellowpanda This topic is about using Azure CLI rather than PowerShell. To use the Azure CLI you must do several steps including registering our Cloud Environment, setting your environment, and then signing in with your credentials. Were you looking for instruction on PowerShell? I'd like to make sure the organization of the content isn't confusing. Thanks for taking the time to provide feedback.

Here is the connect with PowerShell content: https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-powershell-configure-user?view=azs-2008&tabs=az1%2Caz2%2Caz3%2Caz4

Thanks!

#in-progress

**Comment by mattbriggs** [comment]
#please-close
