### ISSUE TITLE
Full index text search options

### ISSUE THREAD

**Issue by Curious-Navigator** [MicrosoftDocs/azure-stack-docs#1333]
[Enter feedback here]
I often mistake the "Title Search" as full index text search and get upsets that I wanted to find something within the product / sub topic document. 

Wish to see the feature for full text index search as a new feature for page enhancements. Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19119cef-de12-31e5-d0b6-b95f2985f57e
* Version Independent ID: 5a7921c1-ac2e-6de8-0e8d-de9f04e457a6
* Content: [Register Azure Stack Hub with Azure - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-registration?view=azs-2008&tabs=az1%2Caz2%2Caz3%2Caz4&pivots=state-disconnected#renew-or-change-registration)
* Content Source: [azure-stack/operator/azure-stack-registration.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-registration.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @PatAltimore
* Microsoft Alias: **patricka**

**Comment by SaiKishor-MSFT** [comment]
Thanks for the feedback! I have assigned the issue to the content author to investigate this and update the document as appropriate.

**Comment by PatAltimore** [comment]
@Curious-Navigator, Thanks for the feedback. If I understand your feedback correctly, you are talking about the filter box above the table of contents. The box above the table of contents is a filter on title rather than a search. There is a search box in the upper right corner that works more like search rather than a filter.

@SaiKishor-MSFT, This is feedback on docs.ms functionality rather than a specific article that I own. If I understand the feedback correctly, I'm not be the right assignee.  

Thanks,
Pat

**Comment by Curious-Navigator** [comment]
Hi Pat,
               Yes, I understand that is filter on title and not the search, but I am curious if there is a way we can do a search  within the subdocument area "Azure Stack Hub 2008" (refer screenshot below), since using the top right corner search  will get results from the entire Microsoft site.


[cid:image001.png@01D71054.42BA4580]

Jegan
Azure Stack Hub CSS
Office: +1 469.775.0253
v-jegankumar@microsoft.com<mailto:v-jegankumar@microsoft.com>

**Comment by sethmanheim** [comment]
#please-close
