### ISSUE TITLE
what does mean make a note

### ISSUE THREAD

**Issue by asobeeh** [MicrosoftDocs/azure-stack-docs#1461]
[Enter feedback here]

what does mean make a note 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3691f8f-4e0a-0ba9-507b-7982a4c31adf
* Version Independent ID: f6937bc3-6d66-503b-9704-fcdefefc2767
* Content: [Delete VM with dependencies on Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/delete-vm?view=azs-2102&tabs=portal)
* Content Source: [azure-stack/user/delete-vm.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/delete-vm.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by MonikaReddy-MSFT** [comment]
@asobeeh - Thanks for reaching out. Can you elaborate your question a little bit more for us to assist you accordingly. Thank you.

**Comment by mattbriggs** [comment]
@asobeeh Thanks for passing along this feedback. I can see a few things I need to make clearer in the article and few sentences that need to be fixed. In terms of "make a note" this just means to write it down or copy and paste it so that you can remember it later. I'll be sure to clarify that in the instructions. Thanks! Matt

#in-progress

**Comment by mattbriggs** [comment]
Updated topic and should be in place in our next build. Thanks again!

#please-close
