### ISSUE TITLE
Creating a custom location of hci-vmoperator failed

### ISSUE THREAD

**Issue by kongou-ae** [MicrosoftDocs/azure-stack-docs#1744]
Hi Azure Stack HCI team,

I'm trying VM provisioning on Azure Portal, then I encountered the following error:

```
PS C:\Users\AzureUser> az customlocation create --resource-group $resource_group --name $customloc_name --cluster-extension-ids "/subscriptions/$subscription/resourceGroups/$resource_group/providers/Microsoft.ResourceConnector/appliances/$resource_name/providers/Microsoft.KubernetesConfiguration/extensions/hci-vmoperator" --namespace hci-vmoperator --host-resource-id "/subscriptions/$subscription/resourceGroups/$resource_group/providers/Microsoft.ResourceConnector/appliances/$resource_name" --location $Location
ApplianceClusterNotRunning: Appliance Cluster: "/subscriptions/<MY SUB ID>/resourceGroups/azshci-eu/providers/Microsoft.ResourceConnector/appliances/AZSHCICLUS-arcbridge" expected state to be Succeeded found: Succeeded and expected status to be Running and found: Connected
```

I guess that this command checked "properties.status" although it should check "properties.provisioningState".

```
PS C:\Users\AzureUser> az resource show --ids /subscriptions/<MY SUB ID>/resourceGroups/azshci-eu/providers/Microsoft.ResourceConnector/appliances/AZSHCICLUS-arcbridge
{
  "extendedLocation": null,
  "id": "/subscriptions/<MY SUB ID>/resourcegroups/azshci-eu/providers/microsoft.resourceconnector/appliances/azshciclus-arcbridge",
  "identity": {
    "principalId": "<MY PRINCIPLE ID>",
    "tenantId": "<MY TENANT ID>",
    "type": "SystemAssigned",
    "userAssignedIdentities": null
  },
  "kind": null,
  "location": "eastus",
  "managedBy": null,
  "name": "azshciclus-arcbridge",
  "plan": null,
  "properties": {
    "distro": "AKSEdge",
    "infrastructureConfig": {
      "provider": "HCI"
    },
    "provisioningState": "Succeeded",
    "publicKey": "",
    "status": "Connected"
  },
  "resourceGroup": "azshci-eu",
  "sku": null,
  "systemData": { [...] },
  "tags": null,
  "type": "Microsoft.ResourceConnector/appliances"
}
```

Best regards.

**Comment by KranthiPakala-MSFT** [comment]
Thanks for reaching out. To better assist your query, could you please share the document link which you are currently following so that we can involve the appropriate team? If your question is generic and not specific to a document feedback, I would recommend you to please post your query in [Microsoft Q&A](https://docs.microsoft.com/answers/products/azure?product=all) forum, where we have our engineers and other community members who will be happy to assist.



Once your query is posted in Microsoft Q&A forum, please do share the link here for reference. 




And If you have a document which you are following and if you think it needs an update, please let us know about that here.



Thank you.

**Comment by kongou-ae** [comment]
Sorry for having open this issue directly, not from docs.microsoft.com.

The document which my issue is related with is as follows:

https://docs.microsoft.com/en-us/azure-stack/hci/manage/azure-arc-enabled-virtual-machines?WT.mc_id=AZ-MVP-5003408#create-a-custom-location-by-installing-azure-arc-resource-bridge

The last command in this section raised the error which I mentioned.

Best.
