### ISSUE TITLE
InvalidRessourceType at "Create a custom location by installing Azure Arc Resource Bridge"

### ISSUE THREAD

**Issue by excelsi** [MicrosoftDocs/azure-stack-docs#1748]
At "Create a custom location by installing Azure Arc Resource Bridge" Step 3 last command i got:

<img width="877" alt="image" src="https://user-images.githubusercontent.com/8747559/143100599-ecd2c86e-dbee-48ce-93a8-8aab1e8386b0.png">

What could be the issue and maybe a solution here?
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b82e60f9-ebed-4011-41b7-3e11a60322ff
* Version Independent ID: 61535b85-bea3-f0b5-f562-fdd08293ed65
* Content: [VM provisioning through Azure portal on Azure Stack HCI - Azure Stack HCI](https://docs.microsoft.com/en-us/azure-stack/hci/manage/azure-arc-enabled-virtual-machines#create-a-custom-location-by-installing-azure-arc-resource-bridge)
* Content Source: [azure-stack/hci/manage/azure-arc-enabled-virtual-machines.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/hci/manage/azure-arc-enabled-virtual-machines.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @ksurjan
* Microsoft Alias: **ksurjan**

**Comment by excelsi** [comment]
Before i had to execute this to get the Deployment running:
az provider register -n Microsoft.ResourceConnector --wait

**Comment by excelsi** [comment]
https://docs.microsoft.com/en-us/azure-stack/hci/manage/azure-arc-enabled-virtual-machines#create-a-custom-location-by-installing-azure-arc-resource-bridge

**Comment by ksurjan** [comment]
This functionality is currently in Preview and available through Early Access Program. We need to whitelist your subscription ID to enable this capability.

This requirement will be lifted in a few weeks once we are in Public Preview.
________________________________
From: excelsi ***@***.***>
Sent: Tuesday, November 23, 2021 11:00 PM
To: MicrosoftDocs/azure-stack-docs ***@***.***>
Cc: Kilol Surjan ***@***.***>; Mention ***@***.***>
Subject: [MicrosoftDocs/azure-stack-docs] InvalidRessourceType at "Create a custom location by installing Azure Arc Resource Bridge" (Issue #1748)


At "Create a custom location by installing Azure Arc Resource Bridge" Step 3 last command i got:

[image]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F8747559%2F143100599-ecd2c86e-dbee-48ce-93a8-8aab1e8386b0.png&data=04%7C01%7Cksurjan%40microsoft.com%7Cf8dd369f86524376116e08d9af1824a6%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637733340560710019%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=XUusb8OHbgzrz9f%2BxrhEYPokDPv4AbBxyYXKyBDieMQ%3D&reserved=0>

What could be the issue and maybe a solution here?
Thanks!

________________________________
Document Details

⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

  *   ID: b82e60f9-ebed-4011-41b7-3e11a60322ff
  *   Version Independent ID: 61535b85-bea3-f0b5-f562-fdd08293ed65
  *   Content: VM provisioning through Azure portal on Azure Stack HCI - Azure Stack HCI<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure-stack%2Fhci%2Fmanage%2Fazure-arc-enabled-virtual-machines%23create-a-custom-location-by-installing-azure-arc-resource-bridge&data=04%7C01%7Cksurjan%40microsoft.com%7Cf8dd369f86524376116e08d9af1824a6%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637733340560710019%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2BXitX8dVIHjhzBwoeFo2UKQlsDtdH1UClD0noYxvN34%3D&reserved=0>
  *   Content Source: azure-stack/hci/manage/azure-arc-enabled-virtual-machines.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fazure-stack-docs%2Fblob%2Fmaster%2Fazure-stack%2Fhci%2Fmanage%2Fazure-arc-enabled-virtual-machines.md&data=04%7C01%7Cksurjan%40microsoft.com%7Cf8dd369f86524376116e08d9af1824a6%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637733340560710019%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=bBmblrsoKCI5uZ4kSDIsSgw0IOoyeQVP%2FEUPD0xfhcI%3D&reserved=0>
  *   Service: azure-stack
  *   Sub-service: azure-stack-hci
  *   GitHub Login: @ksurjan<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fksurjan&data=04%7C01%7Cksurjan%40microsoft.com%7Cf8dd369f86524376116e08d9af1824a6%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637733340560710019%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=zMipeRxK7PZQJPZ3bIcwDzDLrYnfLuZw8CpzESKsWfU%3D&reserved=0>
  *   Microsoft Alias: ksurjan

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fazure-stack-docs%2Fissues%2F1748&data=04%7C01%7Cksurjan%40microsoft.com%7Cf8dd369f86524376116e08d9af1824a6%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637733340560760010%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=NWxYoSF5VENMnkCuw9U95GhgX91evYI0o%2FhsDVAyk6c%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAS2RPCNKWE3OR5DSPOIXDWLUNSER7ANCNFSM5IUNHFAQ&data=04%7C01%7Cksurjan%40microsoft.com%7Cf8dd369f86524376116e08d9af1824a6%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637733340560760010%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=6E%2BF0%2FsGUSlq0CkD7BAcpaetQMOKYYwFrW1Hmzum2O8%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cksurjan%40microsoft.com%7Cf8dd369f86524376116e08d9af1824a6%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637733340560760010%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=aWjrwbLzNpT7LeP4%2F36W8eNEP3dF5msued8n5RGsNnU%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cksurjan%40microsoft.com%7Cf8dd369f86524376116e08d9af1824a6%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637733340560760010%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=wOF949YWjtLfWAKgnEvnNBUflPm0Gy1MLJafk36JLzE%3D&reserved=0>.

**Comment by excelsi** [comment]
OK Bad News for me but thanks anyways...

**Comment by ksurjan** [comment]
If you would like to try this functionality, please provide your subscription ID to whitelist for this feature.
________________________________

**Comment by excelsi** [comment]
4738702d-1b02-4938-bdd2-97b67898d660
Thanks!

**Comment by excelsi** [comment]
Tell me if it's finished and if i need to execute something special additionally. Thanks!

**Comment by ksurjan** [comment]
You are all set. Please try the custom location creation again and it should work now. Please let me know how that goes. Again, the link to Portal during preview is https://aka.ms/HCI-selfserivceVM.
________________________________

**Comment by excelsi** [comment]
Im now at Step 7 it fails with:

<img width="909" alt="image" src="https://user-images.githubusercontent.com/8747559/143471608-422ebf94-9c23-4686-8139-ab4a2d85ef93.png">

On the Azure Portal i can see:

<img width="987" alt="image" src="https://user-images.githubusercontent.com/8747559/143471684-5ed24ebd-706d-48fa-9082-ece47d4cfc43.png">

How can check how the hearbeat is going? Maybe locally on the Linux VM on the HCI?
What i can see here taht the VM has a high memory pressure which i'm wondering abbout (because of the mentioned Requirements 6GB RAM and VM is configured with 8GB):

<img width="767" alt="image" src="https://user-images.githubusercontent.com/8747559/143472201-56b371f0-6aa4-4d37-99de-671e4a35a094.png">

The Link https://aka.ms/HCI-selfserivceVM goes to Bing directly ;-)
Thanks!

**Comment by excelsi** [comment]
Now Step 7 was successful :-)

**Comment by excelsi** [comment]
At the moment i cannot select the custom location and the VM Template

<img width="602" alt="image" src="https://user-images.githubusercontent.com/8747559/143477250-1e13cbfd-cff2-4051-ba24-6a59883ee32f.png">

I finished the steps of:
https://docs.microsoft.com/en-us/azure-stack/hci/manage/azure-arc-enabled-virtual-machines#create-virtual-network-and-gallery-image

I can see my custom location and i have the Owner Rights:

<img width="815" alt="image" src="https://user-images.githubusercontent.com/8747559/143477389-55986244-99e9-426c-894c-ac0212c28338.png">

<img width="914" alt="image" src="https://user-images.githubusercontent.com/8747559/143477503-a283fa6e-b729-47ea-a633-0a181297a2f0.png">

**Comment by kongou-ae** [comment]
I encountered the same issue.
![image](https://user-images.githubusercontent.com/3410186/143600961-37652855-5ded-4e16-8b40-84a104558d02.png)

**Comment by kongou-ae** [comment]
Hi @excelsi ,

I guess that we need to use https://aka.ms/hci-selfservicevm/ to create a VM from the portal. In my case, the portal can show custom locations with this URL.

But I encounter the new issue... 
https://github.com/MicrosoftDocs/azure-stack-docs/issues/1749

Best

**Comment by excelsi** [comment]
Thanks for the right link it worked but i still have also your issue:

https://github.com/MicrosoftDocs/azure-stack-docs/issues/1749#issuecomment-980763887
