### ISSUE TITLE
Add ASH version support matrix compared with OEM baseline version

### ISSUE THREAD

**Issue by CHDAFNI-MSFT** [MicrosoftDocs/azure-stack-docs#1817]
My understand is that Operators should only update ASH up to version supported by OEM's baseline version.

This information (correlation of OEM baseline version and ASH version supportability) doesn't appear to be called out on this page (or anywhere I've easily found), if it doesn't exist, please consider adding it to this page. If it does exist elsewhere, consider linking to it as a 'Note' on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 941ac84e-375d-186f-2a6e-6bac7f67f732
* Version Independent ID: 87dbf3d2-3bfa-a7d4-bc42-8617b663186d
* Content: [Azure Stack Hub Ruggedized OEM Release Notes - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/ruggedized/oem-release-notes-rca#feedback)
* Content Source: [azure-stack/ruggedized/oem-release-notes-rca.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/ruggedized/oem-release-notes-rca.md)
* Service: **azure-stack**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by PriyankaRudramaina** [comment]
@CHDAFNI-MSFT,
Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

@sethmanheim -Requesting you to review this doc and update the information as appropriate please.

**Comment by sethmanheim** [comment]
Thanks for the feedback @CHDAFNI-MSFT. This is the response I got from the engineering team:

"Unless stated otherwise the latest version of Hub should be supported irrespective of which OEM update package is installed if it is still a supported OEM package.  We have historically been maintaining an N-2 support strategy for both of the OEM package and Hub to allow operators to electively defer installing either type of update if necessary so it isn’t required to always be running both the latest version of each.

Having said that, the recommendation is to try to maintain having the latest officially released versions of both the OEM package and the Hub version.  This assures the solution has both the latest Hub fixes as well as the latest drivers and firmware."

**Comment by CHDAFNI-MSFT** [comment]
I understand the feedback presented as it relates to what I assume was just for 1st party OEM package.

Are you open to adding a note that reflects the first paragraph response (or similar)

`Unless stated otherwise the latest version of Hub should be supported irrespective of which OEM update package is installed if it is still a supported OEM package. We have historically been maintaining an N-2 support strategy for both of the OEM package and Hub to allow operators to electively defer installing either type of update if necessary so it isn’t required to always be running both the latest version of each.`

**Comment by sethmanheim** [comment]
It sounds like the engineering team would prefer to defer such a change until after the next release, and that it should probably go [in this article](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-servicing-policy). Thanks again for the feedback! #please-close
