### ISSUE TITLE
Missing Required ARC Agent Install Url

### ISSUE THREAD

**Issue by DellProSupportGse** [MicrosoftDocs/azure-stack-docs#2084]
When you install the ARC agent a redirect URL https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409 is called which redirects you to https://onegetcdn.azureedge.net/providers/providers.masterList.feed.swidtag and this is NOT listed as a required Url. Please add onegetcdn.azureedge.net port 443 to the required Url's.

**Comment by ManikaDhiman** [comment]
@tiaramathur Could you please look into this and let me know if any doc changes are required? Thanks!

**Comment by ManoharLakkoju-MSFT** [comment]
@DellProSupportGse 
Thanks for your feedback! We will investigate and update as appropriate.

It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!

**Comment by ManoharLakkoju-MSFT** [comment]
@DellProSupportGse 
Since we have not heard back from you, we will now proceed to close this thread.
If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by DellProSupportGse** [comment]
Sorry for the delayed response. I was offline for the holidays. 
I discovered these URLs while repairing the ARC agents on Azure Stack HCI Nodes.

**Comment by ManoharLakkoju-MSFT** [comment]
@DellProSupportGse It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!

**Comment by DellProSupportGse** [comment]
The issue is that the ARC agent is not installed when running Register-AzureStackHCI. When we manually download and install the ARC agent. Here is the error message  
![image](https://user-images.githubusercontent.com/79069476/204613267-0d9e0647-5285-474c-9ce9-89bc47d292d3.png)
When we investigate the stackhci.ps1 we find URL https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409 is called which redirects you to https://onegetcdn.azureedge.net/providers/providers.masterList.feed.swidtag. The onegetcdn.azureedge.net URL is not in the list as a required, but it is to be able to install the ARC agent and activate it. 

Side note: Any go.microsoft.com redirects will fail in highly restrictive environments as they are all redirects to other locations like a DNS alias. Would be better to list all the locations instead of go.microsoft.com.

**Comment by ManoharLakkoju-MSFT** [comment]
@DellProSupportGse 
Thank you for your feedback!

Since this issue isn't directly related to improving our docs, and to gain a better understanding of your issue, I'd recommend working closer with our support team via an [Azure support request] (https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request). Or you can leverage our Q&A forum by posting your issue there so our community, and MVPs can further assist you in troubleshooting this issue or finding potential workarounds.

[Teams Q&A forum] (https://docs.microsoft.com/en-us/answers/topics/46488/office-teams-windows-itpro.html) for technical questions about the configuration and administration of Microsoft Teams on Windows.
[Microsoft Teams Community forum] (https://answers.microsoft.com/en-us/msteams/forum?sort=LastReplyDate&dir=Desc&tab=All&status=all&mod=&modAge=&advFil=&postedAfter=&postedBefore=&threadType=All&isFilterExpanded=false&page=1)
Thank you for your time and patience throughout this issue.

**Comment by DellProSupportGse** [comment]
Is it not clear than any go.microsoft.com link redirects to another location and if that location is not listed in the requirements, it will fail and cause the registration process to fail?
