### ISSUE TITLE
Usage and billing for Disconnected mode ?

### ISSUE THREAD

**Issue by rboro-home** [MicrosoftDocs/azure-stack-docs#2101]
Does this page assume connected mode deployment ? How is usage and billing done for disconnected mode ?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ac952c24-f5eb-9b49-ce4c-43f423d00d91
* Version Independent ID: 4813b399-514b-0fd4-78ac-32f962abf82d
* Content: [Customer billing and chargeback in Azure Stack Hub - Azure Stack Hub](https://learn.microsoft.com/en-us/azure-stack/operator/azure-stack-billing-and-chargeback?view=azs-2206)
* Content Source: [azure-stack/operator/azure-stack-billing-and-chargeback.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/operator/azure-stack-billing-and-chargeback.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by ManoharLakkoju** [comment]
@rboro-home 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@rboro-home 
Thank you for your feedback! 
Since this issue isn't directly related to improving our docs, and to gain a better understanding of your issue, I'd recommend working closer with our support team via an [Azure support request] (https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request). Or you can leverage our Q&A forum by posting your issue there so our community, and MVPs can further assist you in troubleshooting this issue or finding potential workarounds. 
[Teams Q&A forum] (https://docs.microsoft.com/en-us/answers/topics/46488/office-teams-windows-itpro.html) for technical questions about the configuration and administration of Microsoft Teams on Windows.
[Microsoft Teams Community forum] (https://answers.microsoft.com/en-us/msteams/forum?sort=LastReplyDate&dir=Desc&tab=All&status=all&mod=&modAge=&advFil=&postedAfter=&postedBefore=&threadType=All&isFilterExpanded=false&page=1)
Thank you for your time and patience throughout this issue.
