### ISSUE TITLE
Convert-WindowsImage

### ISSUE THREAD

**Issue by aricbernard** [MicrosoftDocs/azure-stack-docs#2130]
The specified command using Convert-WindowsImage on a client machine is STILL broken due to the of the published Convert-WindowsImage module trying to use the passthru parameter with the Dismount-DiskImage cmdlet.  That param has not existed in the dismount cmdlet since 1809.  Its been several years now, so fix the cmdlet or provide an alternative method!!!!!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 842bf434-fd3f-5a56-4dee-794858175bed
* Version Independent ID: 779df781-d6a7-0a43-1f1a-2fc66eb9e82f
* Content: [Deploy SDN using Windows Admin Center - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/deploy/sdn-wizard)
* Content Source: [azure-stack/hci/deploy/sdn-wizard.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/deploy/sdn-wizard.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **v-mandhiman**

**Comment by AjayBathini-MSFT** [comment]
@aricbernard 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
Hi @aricbernard 
Thank you for your feedback! 
Since this issue isn't directly related to improving our docs, and to gain a better understanding of your issue, I'd recommend working closer with our support team via an [Azure support request] (https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request).
