### ISSUE TITLE
Cannot install Windows Admin Center in gateway mode using the script provided

### ISSUE THREAD

**Issue by dv00000** [MicrosoftDocs/azure-stack-docs#2343]
Cannot install Windows Admin Center in gateway mode using the script provided.

The error is 
[AdminCenter] Processing data from remote server AdminCenter failed with
the following error message: The I/O operation has been aborted because of
either a thread exit or an application request. For more information, see
the about_Remote_Troubleshooting Help topic.
    + CategoryInfo   : OpenError: (AdminCenter:String) [], PSRemotingTransportException
    + FullyQualifiedErrorId : WinRMOperationAborted,PSSessionStateBroken

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 997dd27c-a77c-76ca-fd9a-b411c7155b9e
* Version Independent ID: 304722a4-5966-0e19-53db-39555b07c8d2
* Content: [Tutorial on creating a private forest environment and virtual machines for an Azure Stack HCI cluster - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/deploy/tutorial-private-forest#install-windows-admin-center-in-gateway-mode)
* Content Source: [azure-stack/hci/deploy/tutorial-private-forest.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/deploy/tutorial-private-forest.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by ManoharLakkoju-MSFT** [comment]
@dv00000 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@dv00000
It looks like you're encountering an error message while installing Windows Admin Center in gateway mode using the script provided in the tutorial. This error message indicates that the I/O operation has been aborted because of either a thread exit or an application request.


To troubleshoot this issue, you can try the following steps: 

1.Check if the Windows Remote Management (WinRM) service is running on the target server. You can do this by running the following command in an elevated PowerShell session:

Get-Service WinRM

 If the service is not running, you can start it by running the following command:
 
 Start-Service WinRM

2.Check if the target server is configured to allow remote PowerShell sessions. You can do this by running the following command in an elevated PowerShell session:

Get-Item WSMan:\localhost\Service\AllowUnencrypted

 If the value of the AllowUnencrypted property is false, you can enable it by running the following command:

 Set-Item WSMan:\localhost\Service\AllowUnencrypted $true

3.Check if the target server is configured to allow remote connections. You can do this by running the following command in an elevated PowerShell session:

Get-NetFirewallRule -DisplayName "Windows Remote Management (HTTP-In)"

 If the rule is not enabled, you can enable it by running the following command:

 Enable-NetFirewallRule -DisplayName "Windows Remote Management (HTTP-In)"
 
 If you are still experiencing issues after trying these steps, I'd recommend working closer with our support team via an [Azure support request] (https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request).
Thank you for your time and patience throughout this issue.

**Comment by ManoharLakkoju-MSFT** [comment]
@dv00000 
It looks like you're encountering an error message while installing Windows Admin Center in gateway mode using the script provided in the tutorial. This error message indicates that the I/O operation has been aborted because of either a thread exit or an application request.


To troubleshoot this issue, you can try the following steps:



1.Check if the Windows Remote Management (WinRM) service is running on the target server. You can do this by running the following command in an elevated PowerShell session:

Get-Service WinRM

 If the service is not running, you can start it by running the following command:

 Start-Service WinRM

2.Check if the target server is configured to allow remote PowerShell sessions. You can do this by running the following command in an elevated PowerShell session:

Get-Item WSMan:\localhost\Service\AllowUnencrypted

 If the value of the AllowUnencrypted property is false, you can enable it by running the following command:

 Set-Item WSMan:\localhost\Service\AllowUnencrypted $true


3.Check if the target server is configured to allow remote connections. You can do this by running the following command in an elevated PowerShell session:

Get-NetFirewallRule -DisplayName "Windows Remote Management (HTTP-In)"

 If the rule is not enabled, you can enable it by running the following command:

 Enable-NetFirewallRule -DisplayName "Windows Remote Management (HTTP-In)"
 
If you are still experiencing issues after trying these steps, I'd recommend working closer with our support team via an [Azure support request] (https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request).
Thank you for your time and patience throughout this issue.

**Comment by dv00000** [comment]
Thanks for the prompt response!

My issue was fixed. The cause is that installing Windows Admin Center will restart WinRM services, which will terminate all remote PowerShells sessions. So I decided to install the Admin Center from a local PowerShell of Admin Center VM (after copying the file from DC) instead of installing remotely, then copy the certificate from AdminCenter VM to DC VM. Finally, restart WinRM of both VMs.
