### ISSUE TITLE
Expanding in Windows Admin Center no longer working

### ISSUE THREAD

**Issue by ContreBombarde** [MicrosoftDocs/azure-stack-docs#2460]
_Please do not close this automatically; I want to know if this is a documentation issue or if something else is going on._

I've expanded volumes before in WAC, but now it's throwing the following error:

> Enable CredSSP 
> Error: Cannot read properties of undefined (reading 'toLocaleLowerCase')

Enabling/disabling CredSSP has no impact. The issue seems to be present in all of the following versions:

- WAC 2211
- WAC 2306
- Cluster Manager extension 2.251.0
- Cluster Manager extension 2.263.0

I'm not sure when this began, but possibly with a recent Windows update (see https://techcommunity.microsoft.com/t5/windows-admin-center/wac-2211-error-cannot-read-properties-of-undefined-reading/m-p/3850916). 

Is there some pre-req or change to be aware of for this to work currently? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ee62314f-c300-755e-5554-ca8494c5b5c5
* Version Independent ID: b23a1eb4-e35a-e5e3-bda4-8a49d0249e96
* Content: [Manage volumes in Azure Stack HCI and Windows Server - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/manage/manage-volumes?tabs=windows-admin-center#expand-volumes)
* Content Source: [azure-stack/hci/manage/manage-volumes.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/manage/manage-volumes.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

Thank you!

**Comment by Naveenommi-MSFT** [comment]
@ContreBombarde 
It would be great if you could add a link to the Microsoft documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!

**Comment by ContreBombarde** [comment]
@Naveenommi-MSFT Thank you, Naveenommi. It's under the Windows Admin Center section under Expand Volumes here: 
https://learn.microsoft.com/en-us/azure-stack/hci/manage/manage-volumes?tabs=windows-admin-center#expand-volumes.

**Comment by Naveenommi-MSFT** [comment]
@ContreBombarde 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@ContreBombarde 
It seems that you are facing an issue with expanding volumes in Windows Admin Center. The error message you are seeing suggests that there might be an issue with the CredSSP configuration.

To resolve this issue, you can try the following steps:

Open PowerShell as an administrator on the machine where Windows Admin Center is installed.

Run the following command to enable CredSSP:

Enable-WSManCredSSP -Role server
Run the following command to enable CredSSP for the client

Enable-WSManCredSSP -Role client -DelegateComputer *
Restart the Windows Admin Center service.

After completing these steps, try expanding the volumes again in Windows Admin Center and see if the issue is resolved. If the issue persists, you may want to check if there are any updates available for Windows Admin Center or the Cluster Manager extension.

I hope this helps! Let me know if you have any further questions.
I'd recommend working closer with our support team via an [Azure support request] (https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request).
