### ISSUE TITLE
Documentation for newer version?

### ISSUE THREAD

**Issue by DarrylvanderPeijl** [MicrosoftDocs/azure-stack-docs#2469]
The documentation got updated and now has the ability for setting the "IPAllocationMethod". The latest AZ extension of azurestackhci, version 0.2.6, does not know this parameter. It also does not know the parameter "vm-switch-name".

Is there a new version coming?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4801619b-bc5d-1091-0f03-128acbd7e792
* Version Independent ID: ec4d09c1-3d99-7077-90c9-6e6352877183
* Content: [Create virtual networks for Azure Stack HCI cluster (preview) - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/manage/create-virtual-networks)
* Content Source: [azure-stack/hci/manage/create-virtual-networks.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/manage/create-virtual-networks.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @alkohli
* Microsoft Alias: **alkohli**

**Comment by YashikaTyagii** [comment]
@DarrylvanderPeijl 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
Hi @DarrylvanderPeijl 

It's possible that the latest version of the Azure Stack HCI extension for Azure CLI does not support the **IPAllocationMethod** and **vm-switch-name** parameters yet.

You can check for updates to the Azure Stack HCI extension by running the following command:
**az extension update --name azurestackhci**
If there is a new version available, this command will update the extension to the latest version.

If there is no new version available, you can try using the Azure Stack HCI PowerShell module instead of the Azure CLI to create virtual networks with the IPAllocationMethod and vm-switch-name parameters.

You can install the Azure Stack HCI PowerShell module by running the following command:
**Install-Module -Name AzureStackHCI**
After installing the module, you can use the **New-AzsHciVirtualNetwork** cmdlet to create virtual networks with the **IPAllocationMethod** and **vm-switch-name** parameters.

Here is an example command:
**New-AzsHciVirtualNetwork -Name "MyVirtualNetwork" -AddressPrefix "10.0.0.0/16" -SubnetName "MySubnet" -SubnetAddressPrefix "10.0.0.0/24" -IPAllocationMethod "Static" -VmSwitchName "MyVmSwitch"**
This command creates a virtual network named **"MyVirtualNetwork"** with a subnet named **"MySubnet"** and an IP allocation method of "Static". The virtual network is associated with a virtual switch named **"MyVmSwitch"**.

**Comment by DarrylvanderPeijl** [comment]
Documentation has rolled back:

https://github.com/MicrosoftDocs/azure-stack-docs/commit/dafec3f89c779734b95d5b3abc35947bfeb99a2d

Case closed.
