### ISSUE TITLE
Invoke-AzStackHciArcIntegrationValidation : The term 'Invoke-AzStackHciArcIntegrationValidation' is not recognized as the name of a cmdlet, function, script file, or operable program.

### ISSUE THREAD

**Issue by PennyMa427** [MicrosoftDocs/azure-stack-docs#2476]
![image](https://github.com/MicrosoftDocs/azure-stack-docs/assets/137464348/fe283b07-b1d9-4dce-8e41-4e2f093a3ed1)

Module is up-to-date, Version                     : 1.2100.2321.143

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 83ea8dd1-da0e-c216-4f40-9588d84999fb
* Version Independent ID: e100da9c-3d71-eb62-173b-0fcccf4417f5
* Content: [Use Azure Stack HCI Environment Checker to assess deployment readiness (preview) - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/manage/use-environment-checker?tabs=connectivity)
* Content Source: [azure-stack/hci/manage/use-environment-checker.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/manage/use-environment-checker.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @alkohli
* Microsoft Alias: **alkohli**

**Comment by YashikaTyagii** [comment]
@PennyMa427 
It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!!

**Comment by PennyMa427** [comment]
i'm following https://learn.microsoft.com/en-us/azure-stack/hci/manage/use-environment-checker?tabs=connectivity to check Azure Stack HCI environment. 
after installation, following https://learn.microsoft.com/en-us/azure-stack/hci/manage/use-environment-checker?tabs=arc-integration to check Arc intergration but the command cannot be recognized.

**Comment by YashikaTyagii** [comment]
@PennyMa427 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by YashikaTyagii** [comment]
@PennyMa427 
Thank you for your feedback!

Since this issue isn't directly related to improving our docs, and to gain a better understanding of your issue, I'd recommend working closer with our support team via an [Azure support request](https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request). Or you can leverage our Q&A forum by posting your issue there so our community, and MVPs can further assist you in troubleshooting this issue or finding potential workarounds.

[Teams Q&A forum](https://docs.microsoft.com/en-us/answers/topics/46488/office-teams-windows-itpro.html) for technical questions about the configuration and administration of Microsoft Teams on Windows.
[Microsoft Teams Community forum](https://answers.microsoft.com/en-us/msteams/forum?sort=LastReplyDate&dir=Desc&tab=All&status=all&mod=&modAge=&advFil=&postedAfter=&postedBefore=&threadType=All&isFilterExpanded=false&page=1)
Thank you for your time and patience throughout this issue.

**Comment by PennyMa427** [comment]
it's not related to Teams
