### ISSUE TITLE
Broken script

### ISSUE THREAD

**Issue by colinrippeyfinarne** [MicrosoftDocs/azure-stack-docs#2482]
At the Validate screen after clicking the Validate button all items show as green but I get the following error message appear at the top right:

Message
Error: Fail to initialize cloud deployment: Cannot bind argument to parameter 'Path' because it is null..ToString() Command Arguments ------- --------- Initialize-CloudDeployment.ps1 {JSONFilePath=C:\CloudDeployment\Setup\AnswerFileUnattended.... Initialize-CloudDeployment_temp.ps1 {JsonFilePath=C:\CloudDeployment\Setup\AnswerFileUnattended....

If I then click Next and then click the Deploy button I see another error:

Message
Error: Cloud deployment has not been initialized. You can use Invoke-CloudDeployment.ps1 -JSONFilePath <string> -AzureStackLCMUserCredential <pscredential> -LocalAdminCredential <pscredential> to invoke cloud deployment

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5ae91113-8c41-fdef-a6e4-95899bbaa36f
* Version Independent ID: 1135a6e1-7933-a7ef-5674-7f80aca310b5
* Content: [Deploy Azure Stack HCI interactively via a new configuration file (preview) - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/deploy/deployment-tool-new-file)
* Content Source: [azure-stack/hci/deploy/deployment-tool-new-file.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/deploy/deployment-tool-new-file.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @alkohli
* Microsoft Alias: **alkohli**

**Comment by AjayBathini-MSFT** [comment]
@colinrippeyfinarne 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@colinrippeyfinarne 
It seems like there is an issue with initializing the cloud deployment. The error message suggests that there is a problem with the path parameter being null. This could be due to a missing or incorrect file path.

To troubleshoot this issue, you can try the following steps:

Check the file path: Make sure that the file path specified in the JSONFilePath parameter is correct and the file exists in that location.

Check the JSON file: Make sure that the JSON file is valid and contains all the required parameters. You can validate the JSON file using an online JSON validator.

Check the PowerShell script: Make sure that the PowerShell script is correct and contains all the required parameters. You can also try running the PowerShell script manually to see if it works.

Check the Azure Stack HCI environment: Make sure that the Azure Stack HCI environment is set up correctly and all the required components are installed.

If none of these steps resolve the issue, you can try reaching out to Microsoft support for further assistance.

I'd recommend working closer with our support team via an [Azure support request] (https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request). Or you can leverage our Q&A forum by posting your issue there so our community, and MVPs can further assist you in troubleshooting this issue or finding potential workarounds. 
[Teams Q&A forum] (https://docs.microsoft.com/en-us/answers/topics/46488/office-teams-windows-itpro.html) for technical questions about the configuration and administration of Microsoft Teams on Windows.

**Comment by colinrippeyfinarne** [comment]
Hi @AjayBathini-MSFT thanks for the reply,

Is there another way to have a dialogue with the team who manage the scripts in the deployment package? I have access to a test lab with 5 Azure Stack HCI Dell AX-750 clusters and can test installs and report any results.

**Comment by AjayBathini-MSFT** [comment]
@colinrippeyfinarne 
I'd recommend working closer with our support team via an [Azure support request] (https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request) .
