### ISSUE TITLE
Step 14 is missing & Step 15 throws an error

### ISSUE THREAD

**Issue by craigpay** [MicrosoftDocs/azure-stack-docs#2524]
Step 14 is missing and Step 15 threw this error...

PS V:\Arc-HCI\WorkingDir> az hybridaks proxy --resource-group $resourceGroup --name "aks-hybrid-cluster" --file .\target-config
az : WARNING: Command group 'hybridaks' is in preview and under development. Reference and support levels: 
https://aka.ms/CLI_refstatus
At line:1 char:1
+ az hybridaks proxy --resource-group $resourceGroup --name "aks-hybrid ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (WARNING: Comman...s/CLI_refstatus:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
ERROR: Bad Request({"error":{"code":"NoRegisteredProviderFound","message":"No registered resource provider found for 
location 'westeurope' and API version '2021-10-01-privatepreview' for type 'endpoints'. The supported api-versions are 
'2021-10-06-preview, 2022-05-01-preview, 2023-03-15'. The supported locations are 'eastus, eastus2, westus2, southeastasia, 
westeurope, northeurope, westcentralus, southcentralus, uksouth, australiaeast, francecentral, westus, centralus, 
northcentralus, japaneast, eastasia, koreacentral, westus3, swedencentral, canadacentral, canadaeast, ukwest, brazilsouth, 
switzerlandnorth, southafricanorth, centralindia, uaenorth, norwayeast, australiasoutheast'."}})
ERROR: Error occured while making ARM request: Bad Request({"error":{"code":"NoRegisteredProviderFound","message":"No 
registered resource provider found for location 'westeurope' and API version '2021-10-01-privatepreview' for type 
'endpoints'. The supported api-versions are '2021-10-06-preview, 2022-05-01-preview, 2023-03-15'. The supported locations 
are 'eastus, eastus2, westus2, southeastasia, westeurope, northeurope, westcentralus, southcentralus, uksouth, 
australiaeast, francecentral, westus, centralus, northcentralus, japaneast, eastasia, koreacentral, westus3, swedencentral, 
canadacentral, canadaeast, ukwest, brazilsouth, switzerlandnorth, southafricanorth, centralindia, uaenorth, norwayeast, 
australiasoutheast'."}})
Summary: Unable to fetch relay and static user authentication information

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7e538b3b-303f-eb84-718d-f9da2d14fd91
* Version Independent ID: b7f3f5fe-cfd8-1160-ef1b-f1637f809d53
* Content: [Quickly get started with using Azure CLI to deploy an AKS hybrid cluster on Windows Server in an Azure VM - AKS hybrid](https://learn.microsoft.com/en-us/azure/aks/hybrid/aks-hybrid-preview-azure-vm)
* Content Source: [AKS-Hybrid/aks-hybrid-preview-azure-vm.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/AKS-Hybrid/aks-hybrid-preview-azure-vm.md)
* Service: **azure-stack**
* Sub-service: **aks-hci**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by Naveenommi-MSFT** [comment]
@craigpay 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
@craigpay 
Thanks for reporting this! For Step 14 is missing, We have created a PR for this issue and the changes should go live soon.
https://github.com/Naveenommi-MSFT/azure-stack-docs-pr/pull/1

The error message indicates that there is no registered resource provider found for the specified location and API version for type 'endpoints'. This could be due to a mismatch between the specified location and API version and the supported locations and API versions for the resource provider.
To resolve this issue, you can try specifying a different location or API version that is supported by the resource provider. You can also check the documentation for the resource provider to see the list of supported locations and API versions.

If still having issue, I'd recommend working closer with our support team via an [Azure support request](https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request).

**Comment by Naveenommi-MSFT** [comment]
@craigpay 
We are going to close this thread, if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

#Please-close
