### ISSUE TITLE
Clarification on Public Services and VIP

### ISSUE THREAD

**Issue by smoms** [MicrosoftDocs/azure-stack-docs#267]
Am I correct that all Public IPs and related external-accessible services (including the Portal) are only for connected scenario? Of course for disconnected scenario the Portal would still be accessible but through internal address..!?
thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49f52a1b-0bfa-a51f-dfa3-4422502d0e82
* Version Independent ID: 95213ed3-d96f-8ad9-e442-7c7f29164ebb
* Content: [Network integration considerations for Azure Stack integrated systems](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-network#feedback)
* Content Source: [azure-stack/operator/azure-stack-network.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-network.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by msrini-MSFT** [comment]
@smoms , Thank you for posting your question here. We will investigate and get back to you shortly.

**Comment by mattbriggs** [comment]
@msrini-MSFT Yes. In a disconnected or air-gapped scenario, the local network would be all that would be available. We refer to "public-ip" addresses in Azure Stack to refer to IP addresses accessible outside of the network within Azure Stack, as well. In this case the public IP addresses only be accessible to the disconnected network external to Azure Stack, but not the wider Internet (since it is disconnected.) Thanks for your question. #in-progress

**Comment by smoms** [comment]
@mattbriggs thanks for the clarification, now i understand what is meant for Public IP. Not necessarily an Internet address.

**Comment by mattbriggs** [comment]
#please-close
