### ISSUE TITLE
Add Secret to Key Vault Script QoL Suggestions

### ISSUE THREAD

**Issue by easyveazie** [MicrosoftDocs/azure-stack-docs#345]
https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-solution-template-service-fabric-cluster#add-a-secret-to-key-vault

1.) We already have documentation on how to connect to Azure Stack as a tenant user, so you can remove Login-AzureRMAccount and parameters from the script
https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-powershell-configure-user

2.) I was confused by the resource group creation. I assumed this is the same resource group I would deploy service fabric to, but that requires an empty resource group. A comment to make this more clear would be helpful.

3.) Does this need to be updated to reflect the missing parameters in the screenshot per this link?
https://github.com/MicrosoftDocs/azure-stack-docs/issues/344

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80a333ac-8208-4146-2d99-6b6258b64a3f
* Version Independent ID: 30341430-ba3a-ae9e-5599-5ed618e9213a
* Content: [Deploy a secured Service Fabric cluster in Azure Stack](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-solution-template-service-fabric-cluster#add-a-secret-to-key-vault)
* Content Source: [azure-stack/user/azure-stack-solution-template-service-fabric-cluster.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-solution-template-service-fabric-cluster.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by BryanTrach-MSFT** [comment]
@easyveazie Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by mattbriggs** [comment]
@easyveazie Thanks for your feedback. Some of these items I can address. Other's don't really seem to be things I would should be updated.

1.) I am going to leave these steps here. A user who has been using Azure Stack will be aware that these are the steps to login into Azure Stack. A new users will need these steps, and seems prudent to leave the in place.

2. I have a question out to the engineering team who is more familiar with the specific of the Azure Stack Service Fabric RP. That does look confusing to me as well. It would seem logical to use the resource group created in the PowerShell step, rather than creating a new one "Deploy the Marketplace item" Step 2.

3.) Does this need to be updated to reflect the missing parameters in the screenshot per this link?
#344. I will review.

#in-progress

**Comment by mattbriggs** [comment]
Oh in writing up my question, I see that the PowerShell script is creating the resource group for the KeyVault. Not sure if this should be the same resource group as the cluster. But I have a question out regardless.

**Comment by easyveazie** [comment]
@mattbriggs , when you deploy the Service Fabric template it requires the resource group to be empty. So the keyvault resource group is separate from the service fabric infrastructure.

**Comment by mattbriggs** [comment]
@easyveazie Thanks for following up. From engineering regarding the resrouce groups being different or the same, "It doesn’t have to be... It just makes practical sense in the interest of keeping all secrets and the app in the same RG. But that aside – the dataplane of KV doesn’t distinguish Resource Groups."

**Comment by mattbriggs** [comment]
@please-close
