### ISSUE TITLE
Only Page bob with Premium?

### ISSUE THREAD

**Issue by Chai-NED** [MicrosoftDocs/azure-stack-docs#697]
"Provide high performance and low latency storage. Only support page blobs in premium storage accounts."

Could you clarify this? Does this mean Azure Global does not support Premium block blob?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ef3d725-6a5b-9799-8fe9-b9c6f0e56a6e
* Version Independent ID: c2ba5b5e-1582-953b-cc5f-07b382d94a54
* Content: [Azure Stack Hub storage differences and considerations - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-acs-differences?view=azs-2002)
* Content Source: [azure-stack/user/azure-stack-acs-differences.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-acs-differences.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by mattbriggs** [comment]
@Chai-NED. Thanks for your question. This means that Azure global (rather than Azure Stack Hub) does support **page** blobs with a Premium storage account.  https://azure.microsoft.com/en-us/pricing/details/storage/page-blobs. Block blobs can are also available for standard accounts as well: https://azure.microsoft.com/en-us/pricing/details/storage/blobs/

**Comment by mattbriggs** [comment]
#please-close
