### ISSUE TITLE
Need more documentation about the ability to block administrators from downloading marketplace products

### ISSUE THREAD

**Issue by kongou-ae** [MicrosoftDocs/azure-stack-docs#701]
Hi,

The following feature looks good, but I can't find the documentation related to this feature. We need the document to use this feature.

&gt; Added a new feature to marketplace management that provides the ability to block administrators from downloading marketplace products that are incompatible with their Azure Stack, due to various attributes such as the Azure Stack version or billing model.

Best regards.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6e05517-6ffa-ad32-ec69-d3299492d880
* Version Independent ID: 2d6ffb4c-9134-a390-3f90-2322c9182e76
* Content: [Azure Stack Hub release notes - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/release-notes?view=azs-2002#feedback)
* Content Source: [azure-stack/operator/release-notes.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/release-notes.md)
* Service: **azure-stack**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by femsulu** [comment]
Thanks for your comment. The feedback has been shared with the content owner for further review. Thanks for your patience.

**Comment by sethmanheim** [comment]
@kongou-ae Sorry for the delay, we are in contact with the engineering team who are working on providing more information about this feature. #in-progress

**Comment by sethmanheim** [comment]
@kongou-ae It turns out that only Microsoft can add the attributes that block administrators from downloading marketplace products that are incompatible with their Azure Stack. I have updated the release notes  to clarify this, as well as this section: https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-download-azure-marketplace-item?view=azs-2002#use-the-portal-to-download-marketplace-items. These updates should be live after 3 PM today, PDT. Thanks again for the feedback!

**Comment by sethmanheim** [comment]
#please-close
