### ISSUE TITLE
Custom script deployment

### ISSUE THREAD

**Issue by bsezgin** [MicrosoftDocs/azure-stack-docs#72]
Because Azure RM powershell 2.4.0 version doesn't allow to use hybrid profile, Azure RM powershell 2.3.0 should be used with custom script deployment. Additionaly, since Azure Stack powershell 1.7.0 is incompatible with Azure RM 2.3.0, Azure Stack powershell 1.5.0 or 1.6.0 must be used in conjunction with Azure RM 2.3.0.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dabc86bd-3770-5832-7fa5-d28856998ae6
* Version Independent ID: cbdb8c6f-ad4d-9e3d-a490-f1348b5ccdfa
* Content: [Using SQL databases on Azure Stack](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-sql-resource-provider-deploy)
* Content Source: [azure-stack/operator/azure-stack-sql-resource-provider-deploy.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-sql-resource-provider-deploy.md)
* Service: **azure-stack**
* GitHub Login: @jeffgilb
* Microsoft Alias: **jeffgilb**

**Comment by TravisCragg-MSFT** [comment]
@bsezgin Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate. This is also similar to #18.

**Comment by mattbriggs** [comment]
@bsezgin Thanks for your feedback. Please follow the instructions for installing API Profiles with PowerShell https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-powershell-install. #please-close

**Comment by bsezgin** [comment]
Thank you.

**Comment by xiaofmao** [comment]
Thanks for sharing your feedback! @bsezgin 
While installing SQL RP, the specific PowerShell profile and AzureStack module should be installed. Otherwise you'll get error during the deployment.
https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-sql-resource-provider-deploy#deploy-the-sql-resource-provider-using-a-custom-script
== Install the AzureRM.Bootstrapper module, set the profile and install the AzureStack module ==
== Note that this might not be the most currently available version of Azure Stack PowerShell ==
Install-Module -Name AzureRm.BootStrapper -Force
Use-AzureRmProfile -Profile 2018-03-01-hybrid -Force
Install-Module -Name AzureStack -RequiredVersion 1.6.0
