### ISSUE TITLE
Configure external access to the MySQL hosting server

### ISSUE THREAD

**Issue by CarlosGon** [MicrosoftDocs/azure-stack-docs#778]
i followed the document to add a new mysql hosting server (bitnami Mysql server 8 marketplace item), and noted a few differences that i think we need to adjust and complete.

Title should be : Prepare a MySQL hosting server

1.	The MySQL RP doesn't support caching_sha2_password authentication. MySQL 8.0 servers must be configured to use mysql_native_password.
No explanation for that change. And if the cx create the user to use for adding as hosting server, on mysql, before change this property and restart the mysql service, this user needs to the changed before it can be used.

Change authentication method:
/opt/bitnami/mysql/conf/my.cnf
[mysqld] 
default_authentication_plugin=mysql_native_password

Change plugin for already created user
Mysql&gt; ALTER USER mysqladmin IDENTIFIED WITH mysql_native_password BY 'q######c';

Check user plugin
Mysql&gt;  SELECT user,host,plugin from mysql.user;

2.	We cannot use the bitnami user to login, since it is set to nologin.

3.	Wrong settence ".... log in to MySQL as root, using the root password created earlier."
Default mysql root credential is located  
/home/bitnami/bitnami_credeantials

This is not documented anywhere. It wasn’t easy to find it.

4.	We need to allow 3306 port on inbound rules for that VM 
Not very well explained, that the cx really need to enable that port on portal.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9da7c95f-1749-8818-f96f-c4ae02aa28a6
* Version Independent ID: db6e924d-d8c0-72bc-b0e3-382373ee7588
* Content: [Add MySQL hosting servers in Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-mysql-resource-provider-hosting-servers?view=azs-2002#feedback)
* Content Source: [azure-stack/operator/azure-stack-mysql-resource-provider-hosting-servers.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-mysql-resource-provider-hosting-servers.md)
* Service: **azure-stack**
* GitHub Login: @BryanLa
* Microsoft Alias: **bryanla**

**Comment by TravisCragg-MSFT** [comment]
@CarlosGon Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by BryanLa** [comment]
Thanks for the feedback @CarlosGon. I'll be working through your suggestions with engineering. We'll provide another update when complete.

**Comment by jdm019000** [comment]
I would like to add to this post because I hit all the same issues described above and agree it was not clearly explained. I had the same trouble finding the root password to mysql.  

A couple of extra observations.  
1. If you edit/change the /opt/binami/mysql/conf/my.cnf file to support legacy "mysql_native_password", I believe that you need to restart mysql.  Since this is bitnami, you have to run "sudo /opt/bitnami/ctlscript.sh restart".  Additionlly, this  has be done before creating new users like the sql admin user. Otherwise new user creation in mysql defaults to the newer "caching_sha2_password" method.  
2. if you need to created the user after finding this, then you need to run commands mentioned above, like the below after logging into mysql. 
select host,user, account_locked, plugin  from mysql.user;
update mysql.user set plugin = 'mysql_native_password' where user = 'sqlsa';
3.  Also i am not sure but i had to make a specific user in msyql that included the MySQL RP public IP accress and grant access to that same user, like the below.  All of this was needed in order to add the MySQL hosting adapter. 
create user sqlsa@'<MySQL RP Public IP>' identified by '<adminuser password>';
grant all privileges on *.* to 'sqlsa'@'<MySQL RP Public IP>' with grant option;

**Comment by BryanLa** [comment]
@CarlosGon, @jdm019000 - changes were applied last night. The revised version will republish around 10:15am PDT today.

#please-close
