### ISSUE TITLE
The way to add a vm image with portal is incorrect.

### ISSUE THREAD

**Issue by kongou-ae** [MicrosoftDocs/azure-stack-docs#85]
Hello,

The following way to add a vm image through portal is incorrect.

https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-add-vm-image#add-a-vm-image-through-the-portal

I think that a image in Azure Stack is two types. A is a image which is in a specific subscription. B is a image which is in the platform of Azure Stack. Azure Stack Operator must create a image as B to use a image as Azure Stack Marketplace, but this article introduce a way about A.

Best regards.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6a61eee-2c60-1a86-3e06-fa7689705d18
* Version Independent ID: 28759edc-2b94-e42e-3353-6ebe13b2a90f
* Content: [Add a VM image to Azure Stack](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-add-vm-image#add-a-vm-image-through-the-portal)
* Content Source: [azure-stack/operator/azure-stack-add-vm-image.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-add-vm-image.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by YutongTie-MSFT** [comment]
@kongou-ae 
Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by mattbriggs** [comment]
@kongou-ae  Thanks for your feedback. I need to review the portal steps to identify the issue with the docs and I'll update. Thanks for letting us know. #in-progress

**Comment by mattbriggs** [comment]
@kongou-ae In reviewing the document, the steps to add an image with the cloud operator role in order to make it available via an offer seems correct to me. Can you let me know what failed for you? I'd like to try to rephrase your observation about images in Azure Stack. Please let me know if I am not capturing what you meant correctly. I take you to mean that there are two ways in which you can get an image into the marketplace in Azure Stack. One (your A) are images that are coming from the Azure Marketplace and being made available in the Azure Stack Marketplace. Two (your B) are images that are being loaded into the Azure Stack Marketplace after being placed in a Blob storage account. This topic is about the second type. Please let me know if you are having an issue creating a custom image in an offer or where we can improve our docs to make them less ambiguous or confusing. Thanks again for taking the time to help us improve our docs. #in-progress

**Comment by kongou-ae** [comment]
@mattbriggs  Sorry for my confusing proposal. My suggestion is B which you explained. I think that the procedure about B is as following document which I created to explain my proposal more specifically.

https://github.com/kongou-ae/azure-stack-docs/blob/%2385/azure-stack/operator/azure-stack-add-vm-image.md

**Comment by mattbriggs** [comment]
@kongou-ae Thanks again for your input. I've reviewed your proposal and applied them where appropriate to the document. #please-close

**Comment by mattbriggs** [comment]
#please-close
