### ISSUE TITLE
Build numbers

### ISSUE THREAD

**Issue by rfsonders** [MicrosoftDocs/azure-stack-docs#86]
Hello
Why are there two build numbers for the SQL RP? Both supporting the same Azure Stack build. Reference pages are also misaligned. PowerShell compatibility was fixed with 1.1.30.0 however, 1.1.33.0 is a later build. Which version do we use? Both installs fail with the latest ASDK environment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dabc86bd-3770-5832-7fa5-d28856998ae6
* Version Independent ID: cbdb8c6f-ad4d-9e3d-a490-f1348b5ccdfa
* Content: [Using SQL databases on Azure Stack](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-sql-resource-provider-deploy#prerequisites)
* Content Source: [azure-stack/operator/azure-stack-sql-resource-provider-deploy.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-sql-resource-provider-deploy.md)
* Service: **azure-stack**
* GitHub Login: @jeffgilb
* Microsoft Alias: **jeffgilb**

**Comment by YutongTie-MSFT** [comment]
@rfsonders Thank you for your feedback, could you please share the document you are referring to for this issue?

**Comment by rfsonders** [comment]
This page, with an older update date, is not in sync
https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-sql-resource-provider-deploy#prerequisites

This page, has been updated.
https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-sql-resource-provider-11300

**Comment by YutongTie-MSFT** [comment]
@rfsonders Thanks for the information! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by jeffgilb** [comment]
@mattbriggs please re-assign as I'm off the docs team now.

**Comment by mattbriggs** [comment]
@rfsonders I've passed the following comments along to the technical team.
 - Why are there two build numbers for the SQL RP? Which version do we use?
-  Both installs fail with the latest ASDK environment.

I updated this issue:
- Reference pages are also misaligned. (Updated.)

#in-progress

**Comment by xiaofmao** [comment]
Thanks for sharing your feedback, @rfsonders !
Actually SQL/MySQL RPs have separated release process, instead of releasing along with Azure Stack regular updates. 1.1.33.0 is the current latest version, and 1.1.30.0 is the one before that. Azure Stack 1808 update is the **minimum** Azure Stack version the RP versions could support. That's why you see two SQL RP versions are both corresponded to Azure Stack 1808 update.
About the deployment failure that you mentioned, could you please share a little more information about the versions of ASDK, PowerShell profile, AzureStack module. And what's the exact error that you got during deployment?
For PowerShell profile and AzureStack module, current 1.1.33.0 version of RP requires specific version of PowerShell modules.
https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-sql-resource-provider-deploy#deploy-the-sql-resource-provider-using-a-custom-script
# Install the AzureRM.Bootstrapper module, set the profile and install the AzureStack module
# Note that this might not be the most currently available version of Azure Stack PowerShell
Install-Module -Name AzureRm.BootStrapper -Force
Use-AzureRmProfile -Profile 2018-03-01-hybrid -Force
Install-Module -Name AzureStack -RequiredVersion 1.6.0

**Comment by mattbriggs** [comment]
@xiaofmao Thanks! @rfsonders let me know if you have any additional questions. #please-close

**Comment by rfsonders** [comment]
Team.
Documentation is still not correct.
Please take a look at this page.
https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-sql-resource-provider-deploy

This table is confusing.
Which Azure Stack version aligns with which SQL RP. I see 2 options for 1808.

Minimum Azure Stack version | SQL RP version

Version 1808 (1.1808.0.97) | SQL RP version 1.1.33.0
Version 1808 (1.1808.0.97) | SQL RP version 1.1.30.0
Version 1804 (1.0.180513.1) | SQL RP version 1.1.24.0

**Comment by mattbriggs** [comment]
@rfsonders The Azure Stack Version # corresponds with the SQL RP versions. Both 1.1.33.0 and 1.1.30.0 require Azure Stack Version 1808 or later. Thanks for your feedback, and sorry to have confused you. Thanks, Matt

**Comment by mattbriggs** [comment]
#please-close
